"""add BranchImage path column

Revision ID: 13cd9bdfe4e8
Revises: 5c7e70538fc1
Create Date: 2022-06-17 19:47:10.592316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cd9bdfe4e8'
down_revision = '5c7e70538fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branchimages', sa.Column('image_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branchimages', 'image_path')
    # ### end Alembic commands ###
