"""empty message

Revision ID: 1b3f97cce63c
Revises: 988832a2dfd4
Create Date: 2022-06-23 06:22:13.803793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3f97cce63c'
down_revision = '988832a2dfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'city', ['id'])
    op.create_unique_constraint(None, 'state', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    # ### end Alembic commands ###
