"""empty message

Revision ID: 2828d9cdee25
Revises: c67c30e37cca
Create Date: 2022-06-26 19:23:03.229643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2828d9cdee25'
down_revision = 'c67c30e37cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergoldprice', sa.Column('state_id', sa.Integer(), nullable=False))
    op.add_column('usergoldprice', sa.Column('status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usergoldprice', 'state', ['state_id'], ['id'])
    op.drop_column('usergoldprice', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergoldprice', sa.Column('city', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'usergoldprice', type_='foreignkey')
    op.drop_column('usergoldprice', 'status')
    op.drop_column('usergoldprice', 'state_id')
    # ### end Alembic commands ###
