"""Initial migration.

Revision ID: 369aaa2a4bb0
Revises: 38295a3bee4a
Create Date: 2022-07-02 23:28:16.854216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369aaa2a4bb0'
down_revision = '38295a3bee4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('request_callback', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_callback', 'status')
    op.drop_column('contact_us', 'status')
    # ### end Alembic commands ###
