"""empty message

Revision ID: 38295a3bee4a
Revises: d86c4a6a5e61
Create Date: 2022-06-30 13:50:20.571698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38295a3bee4a'
down_revision = 'd86c4a6a5e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('career', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career', 'status')
    op.drop_column('career', 'position')
    # ### end Alembic commands ###
