"""home page db update

Revision ID: 5693b73e781f
Revises: 369aaa2a4bb0
Create Date: 2023-09-13 11:56:05.642835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5693b73e781f'
down_revision = '369aaa2a4bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_callback', sa.Column('selectoption', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_callback', 'selectoption')
    # ### end Alembic commands ###
