"""Initial migration.

Revision ID: 5c7e70538fc1
Revises: 
Create Date: 2022-06-17 17:50:59.676901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7e70538fc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('state_id', sa.Integer(), nullable=False))
    op.add_column('city', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'city', 'state', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_column('city', 'date')
    op.drop_column('city', 'state_id')
    # ### end Alembic commands ###
