"""empty message

Revision ID: 71015e64d787
Revises: 82622c14414c
Create Date: 2022-06-26 19:24:44.268988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71015e64d787'
down_revision = '82622c14414c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'usergoldprice', 'state', ['state_id'], ['id'])
    op.drop_column('usergoldprice', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergoldprice', sa.Column('city', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'usergoldprice', type_='foreignkey')
    # ### end Alembic commands ###
