"""changes in contact model.

Revision ID: 7cac34155648
Revises: 5693b73e781f
Create Date: 2024-10-02 16:49:01.511521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cac34155648'
down_revision = '5693b73e781f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('is_phone_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_us', 'is_phone_verified')
    # ### end Alembic commands ###
