"""empty message

Revision ID: 82622c14414c
Revises: 2828d9cdee25
Create Date: 2022-06-26 19:24:11.984622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82622c14414c'
down_revision = '2828d9cdee25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usergoldprice', 'state_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'usergoldprice', 'state', ['state_id'], ['id'])
    op.drop_column('usergoldprice', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergoldprice', sa.Column('city', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'usergoldprice', type_='foreignkey')
    op.alter_column('usergoldprice', 'state_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
