"""empty message

Revision ID: 988832a2dfd4
Revises: 13cd9bdfe4e8
Create Date: 2022-06-21 19:38:18.227686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988832a2dfd4'
down_revision = '13cd9bdfe4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('gmap_link', sa.String(length=200), nullable=True))
    op.add_column('branchimages', sa.Column('tag', sa.String(length=100), nullable=True))
    op.add_column('city', sa.Column('state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'city', 'state', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_column('city', 'state_id')
    op.drop_column('branchimages', 'tag')
    op.drop_column('branch', 'gmap_link')
    # ### end Alembic commands ###
