"""Initial migration.

Revision ID: c67c30e37cca
Revises: 1b3f97cce63c
Create Date: 2022-06-26 17:59:27.307577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c67c30e37cca'
down_revision = '1b3f97cce63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currentgoldprice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currentgoldprice',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('carat', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
