"""empty message

Revision ID: d86c4a6a5e61
Revises: 71015e64d787
Create Date: 2022-06-28 13:14:58.919208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86c4a6a5e61'
down_revision = '71015e64d787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'description')
    # ### end Alembic commands ###
