"""changes reverted in contact model.

Revision ID: e6ac4e3b3f3f
Revises: 7cac34155648
Create Date: 2024-10-02 18:16:48.028819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6ac4e3b3f3f'
down_revision = '7cac34155648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_us', 'is_phone_verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('is_phone_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
